fix cfn.sh

diff --git a/init b/init
--- a/init
+++ b/init
@@ -2,6 +2,7 @@
 
 source ./config.sh
 export ENVIRONMENT="$1"
+export TEMP_BUCKET="$2"
 
 if [[ ! "$APPLICATION" =~ ^[A-Z][a-zA-Z0-9]*$ ]]
 then
@@ -11,10 +12,18 @@ then
 
 fi
 
-if [[ ! "$ENVIRONMENT" =~ ^[a-z][a-z0-9]*$ ]]
+if [[ ! "$ENVIRONMENT" =~ ^[a-z0-9]*$ ]]
 then
 
   echo "ERROR: ENVIRONMENT (\$1) must start with an lowercase letter and contain only lowercase letters and numbers"
+  exit 1
+
+fi
+
+if [[ ! "$TEMP_BUCKET" =~ ^[a-z0-9-]*$ ]]
+then
+
+  echo "ERROR: TEMP_BUCKET (\$2) must start with an lowercase letter and contain only lowercase letters, numbers and hyphens"
   exit 1
 
 fi
@@ -58,9 +67,14 @@ else
 
   echo "Initializing $STACK_NAME CloudFormation Stack..."
   
+  aws cloudformation package \
+    --template-file ./build/init.yml \
+    --s3-bucket $TEMP_BUCKET \
+    --output-template-file ./build/packaged.yml \
+  
   aws cloudformation deploy \
     --stack-name "$STACK_NAME" \
-    --template-file ./build/init.yml \
+    --template-file ./build/packaged.yml \
     --capabilities CAPABILITY_IAM CAPABILITY_NAMED_IAM \
     --parameter-overrides \
       "Application=$APPLICATION" \
@@ -72,6 +86,8 @@ else
     --tags \
       "Application=$APPLICATION" \
       "Environment=$ENVIRONMENT" \
+
+  rm -f ./build/packaged.yml
 
   if [ "$ENVIRONMENT" == "master" ]
   then
